version: '3.7'

services:
  webapp:
    build:
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./webapp/src:/home/node/src

  strapi:
    build:
      target: development
    environment:
      NODE_ENV: development
  #  volumes:
  #    - ./strapi/api:/srv/app/api
  #    - ./strapi/config:/srv/app/config
  #    - ./strapi/extensions:/srv/app/extensions
  #    - ./strapi/public:/srv/app/public

  # mongo:
  #   volumes:
  #     - ./data/db:/data/db

  nginx:
    build:
      target: development
    ports:
      - 80:80
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf

  mongo-express:
      image: mongo-express
      restart: always
      ports:
      - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: $DATABASE_USERNAME
        ME_CONFIG_MONGODB_ADMINPASSWORD: $DATABASE_PASSWORD
